// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwctkeacagskeuavjrch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53Y3RrZWFjYWdza2V1YXZqcmNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjUwODAsImV4cCI6MjA2OTA0MTA4MH0.yiBynv0yCmPImbgMYqLpw-ZlQjX7y7HkQ7pudsNoI8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});